In [78]:
import numpy as np

In [80]:
def determ(k):
    a = np.random.rand(k,k)
    return np.linalg.det(a)
determ(10)

0.19455090167693853

In [45]:
def mean_det(k,n):
    x = np.array([determ(k) for i in range(n)])
    return np.average(x), np.std(x)
mean_det(20,10000)

(0.0021446667670133378, 0.20403030964161215)

In [47]:
t = np.array([[
    [0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]
],[
    [-0,-1,-2,-3],
    [-4,-5,-6,-7],
    [-8,-9,-10,-11]
]])
print(t)

[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[  0  -1  -2  -3]
  [ -4  -5  -6  -7]
  [ -8  -9 -10 -11]]]


In [49]:
print(t.shape)

(2, 3, 4)


In [58]:
print(t[0,1,2])

6


In [59]:
print(t[:,1,:])

[[ 4  5  6  7]
 [-4 -5 -6 -7]]


In [62]:
t[1].transpose()

array([[  0,  -4,  -8],
       [ -1,  -5,  -9],
       [ -2,  -6, -10],
       [ -3,  -7, -11]])

In [72]:
a = np.array([
    [1, 2],
    [3, 4]
])
b = a.transpose().copy()
print(a)
print(b)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [81]:
a == b

array([[ True, False],
       [False, False]])