In [7]:
import numpy as np

In [21]:
s = [i for i in range(4)]

In [20]:
j = np.random.randint(0, 3, (4))
print(j)

[0 0 1 1]


In [22]:
s

[0, 1, 2, 3]

In [8]:
p = np.random.randint(0, 10, (4,5))
print(p)

[[3 1 6 9 2]
 [3 7 0 6 0]
 [3 0 3 4 7]
 [3 6 2 7 3]]


In [23]:
p[s,j]

array([3, 3, 0, 6])